### ISSUE TITLE
generated app still has http client in it

### ISSUE THREAD

**Issue by pm100** [fvilches17/CleanBlazor#1]
Since the purpose is to strip out all unnecessary junk I do not think the plumbing for getting the weather json needs to be there

**Comment by fvilches17** [comment]
hi @pm100 thanks trying out CleanBlazor.

Just to confirm, are you specifically referring to the wasm version (e.g. `dotnet new cleanblazorserverwasm`)?

i.e. line 9 in the screenshot below?

![image](https://user-images.githubusercontent.com/13502806/147721202-fa62d0c4-2a58-4972-a92e-fbd8041c2a17.png)

**Comment by pm100** [comment]
Yes that's what I am referring to

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fvilches17** [comment]
Right.

Yeah I see your point. I can imagine some blazor apps (e.g. a web calculator) not needing the http client.

Please feel free to create a pull request.

**Comment by pm100** [comment]
now I am having second thoughts. My app doesnt need connectivity but others may do, in fact thats probably the majority. So maybe just close this. It would be nice if we could do 'dotnet new cleanblazorweb --http --auth', ie choose which extra bits of glue are needed. I dont know enough about templates tho

**Comment by fvilches17** [comment]
hi @pm100 yeah it seems like common functionality and just one line to remove in case you don't need it. I'll go ahead and close this one.
