### ISSUE TITLE
Server hosted wasm support

### ISSUE THREAD

**Issue by km-hussain-in** [fvilches17/CleanBlazor#2]
Provide corresponding support for 

dotnet new blazorwasm --hosted

**Comment by fvilches17** [comment]
hi @km-hussain-in good suggestion.

Will add support

**Comment by fvilches17** [comment]
@km-hussain-in 

Support has been added in PR #3 

You can get the latest by running ```dotnet new --update-apply``` in any command prompt 

Rr simply install from scratch if not already installed on your machine ```dotnet new --install FriscoVInc.DotNet.Templates.CleanBlazor```

You can see the new flags in the UI if using Visual Studio, or if using the dotnet cli you can include the help command to view all flags. E.g. ```dotnet new cleanblazorwasm -h```

Feel free to make any further suggestions or report any bugs if any.
